### ISSUE TITLE
Unsupported Version error thrown for each entry in file

### ISSUE THREAD

**Issue by trescube** [mhr3/unzip-stream#9]
I noticed that in the [version check lines](https://github.com/mhr3/unzip-stream/blob/master/lib/unzip-stream.js#L209-L221), an error is emitted for every zip file entry.  I'm not intimately familiar with the zip file format but it looks like each file has a version in its header even though this appears to be a normalization problem with the format.  In that case, would it suffice to emit an error on the unzip stream itself instead of each individual entry since, presumably, each entry has the same version. That is, instead of:

```javascript
setImmediate(() => {
  entry.emit("error", new Error(message));
});
```

change the code to:

```javascript
setImmediate(() => {
  self.emit("error", new Error(message));
});
```

Please let me know if I'm completely misinterpreting the intent of the code or zip file format.  The same logic would apply for the encrypted flag.  There don't appear to be any other events emitted for entry instances.

**Comment by mhr3** [comment]
There's many zip programs that only use later version in the entry if it's actually necessary - ie version 4.5 only if a specific file is larger than 4GB. So you could have a single file in a large archive that uses 4.5 and the rest uses 2.1 - now because one of the use cases of unzip-stream is to extract only a specific file (using the Parse method), a single entry with an unsupported version shouldn't break the entire parse process.

That being said, I guess for the Extract() method it would be useful to have an option that stops the extraction and emits the error on the stream itself, not the entry (such an option should perhaps even be on by default).

Bottomline, works as desired, though there's room for improvement. Patches welcome :)

**Comment by trescube** [comment]
Ah, interesting, thanks!  Thanks for the guidance, I'll get something together within the next few days.
